### ISSUE TITLE
PYTHON variable issue when making pip-installable

### ISSUE THREAD

**Issue by kstoreyf** [kstoreyf/suave#1]
## General information

- versions: smoothcorrfunc 0.0.0, Corrfunc: 2.3.2
- platform: linux
- installation method (pip/source/other?): source

## Issue description 

I am trying to make my package installable via pip. I have edited the setup.py and common.mk files to make a new distribution name and version number. When I upload the distribution to testpypi, it seems fine, but then when I try to install on another system, it hits an error because of the PYTHON variable in common.mk.

I figured out that the setup.py file checks that the python executable that ran the setup script is the same as the one in common.mk, and if it's not, it updates the common.mk one to the python path used. This means that my miniconda path ends up hardcoded, so when I try to install on another system it fails.

## Actual behavior

This is the line that updates the PYTHON variable and causes the issue: 
`python setup.py sdist`
where python points to my miniconda python installation, `/home/users/ksf293/miniconda3/bin/python3.`

Then I do 
`python -m twine upload --repository testpypi --skip-existing dist/*`

The package is successfully uploaded to testpypi here:
`https://test.pypi.org/project/smoothcorrfunc/0.0.0`
and can be installed with:
`pip install -i https://test.pypi.org/simple/ smoothcorrfunc==0.0.0`

When I try this on a different system, I get the error:
`RuntimeError: command = /home/users/ksf293/miniconda3/bin/python3 -c 'from __future__ import print_function; import sys; print(sys.executable)' failed with stdout = b'' stderr = b'/bin/sh: /home/users/ksf293/miniconda3/bin/python3: No such file or directory\n' status 127`

## Expected behavior

For now I edited setup.py to not update common.mk, and just set PYTHON:=python in common.mk. 

I did this for an updated pip distribution, so doing
`pip install -i https://test.pypi.org/simple/ smoothcorrfunc==0.0.1`
installs with no errors.

Is there a better solution?

**Comment by kstoreyf** [comment]
@manodeep @lgarrison, any wisdom here? thanks!

**Comment by manodeep** [comment]
If you compile the code, then `common.mk` will get modified; but that modification will remain as an uncommitted change. I create the source distribution after restoring `common.mk` to the normal (i.e., `PYTHON := python`) value (you can also do a `git checkout -- common.mk` to remove that change). 

I should probably document the steps to create a release of Corrfunc (including updating the version numbers in multiple places) - such a document probably would have been helpful for you.

**Comment by lgarrison** [comment]
Actually @manodeep, it looks like you might have fixed this bug in this commit 6 months ago? https://github.com/manodeep/Corrfunc/commit/e6cd90ba23d5723aa87b0141d42336ac46bd4238

So maybe the fix is as easy as merging upstream into your branch, or at least cherry-picking this commit if merging is complicated at this point.

**Comment by manodeep** [comment]
Heh! Just came here to point that out - what @lgarrison said :)

**Comment by lgarrison** [comment]
I love it when I forget I fixed a bug, it's a gift from my past self!

**Comment by kstoreyf** [comment]
amazing thank you for the quick replies! been meaning to merge in 2.3.3... i'll see how complicated that seems, and otherwise just grab that commit.

and yes @manodeep documentation of the steps to release would have been helpful, though it wasn't too bad to figure out! i'll write up what i did at least for posterity.

**Comment by kstoreyf** [comment]
fixed via sync with Corrfunc 2.3.4 e59fd57
